export const gameTypes: string[] = [
  "Action-adventure",
  "Adventure",
  "Fighting",
  "FPS",
  "TPS",
  "RPG",
  "Battle Royal",
  "Platforming",
  "Strategy",
  "Simulation",
  "Sport",
  "Casual",
  "Survival-horror",
  "Survival",
];
